//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indoor_navigation_backend.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapEntities : DbContext
    {
        public MapEntities()
            : base("name=MapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Rectangle> Rectangles { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
