//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indoor_navigation_backend.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rectangle
    {
        public int id { get; set; }
        public double northEastLatitude { get; set; }
        public double northEastLongitude { get; set; }
        public double southWestLatitude { get; set; }
        public double southWestLongitude { get; set; }
    }
}
