//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indoor_navigation_backend.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int id { get; set; }
        public Nullable<int> startPointId { get; set; }
        public Nullable<int> endPointId { get; set; }
        public Nullable<int> floorId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> externalId { get; set; }
    }
}
